<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/config/config.php';
require_once dirname(__DIR__) . '/core/Database.php';
require_once dirname(__DIR__) . '/core/Router.php';
require_once dirname(__DIR__) . '/core/Controller.php';
require_once dirname(__DIR__) . '/core/Model.php';
require_once dirname(__DIR__) . '/core/Auth.php';
require_once dirname(__DIR__) . '/app/Controllers/BaseController.php';
require_once dirname(__DIR__) . '/app/Controllers/HomeController.php';
require_once dirname(__DIR__) . '/app/Controllers/AuthController.php';
require_once dirname(__DIR__) . '/app/Controllers/SetupController.php';
require_once dirname(__DIR__) . '/app/Controllers/CompanyController.php';
require_once dirname(__DIR__) . '/app/Controllers/ModuleController.php';
require_once dirname(__DIR__) . '/app/Controllers/ManagementController.php';
require_once dirname(__DIR__) . '/app/Models/UserModel.php';
require_once dirname(__DIR__) . '/app/Models/RoleModel.php';
require_once dirname(__DIR__) . '/app/Models/EmployeeModel.php';
require_once dirname(__DIR__) . '/app/Models/CompanyModel.php';
require_once dirname(__DIR__) . '/app/Models/ProjectModel.php';
require_once dirname(__DIR__) . '/app/Models/RequisitionModel.php';

(new CompanyModel())->getCompanies();

$routes = [
    '/' => ['HomeController', 'index'],
    '/login' => ['AuthController', 'login'],
    '/super-admin/login' => ['AuthController', 'superAdminLogin'],
    '/logout' => ['AuthController', 'logout'],
    '/stop-impersonation' => ['AuthController', 'stopImpersonation'],
    '/setup' => ['SetupController', 'index'],
    '/setup/select-company' => ['SetupController', 'selectCompany'],
    '/company/workspace' => ['CompanyController', 'workspace'],
    '/company/select' => ['CompanyController', 'select'],
    '/company/set-active' => ['CompanyController', 'setActive'],
    '/company/create' => ['CompanyController', 'create'],
    '/company/custom-module/create' => ['CompanyController', 'createCustomModule'],
    '/company/custom-module/delete' => ['CompanyController', 'deleteCustomModule'],
    '/modules' => ['ModuleController', 'index'],
    '/modules/custom' => ['ModuleController', 'customModule'],
    '/modules/workflow' => ['ModuleController', 'workflow'],
    '/modules/workflow/save' => ['ModuleController', 'saveWorkflow'],
    '/modules/requisition-form' => ['ModuleController', 'requisitionForm'],
    '/modules/requisition-form/save' => ['ModuleController', 'saveRequisitionForm'],
    '/modules/workflow/levels/create' => ['ModuleController', 'createWorkflowLevel'],
    '/modules/workflow/levels/delete' => ['ModuleController', 'deleteWorkflowLevel'],
    '/modules/inventory' => ['ModuleController', 'inventory'],
    '/modules/projects' => ['ModuleController', 'projects'],
    '/modules/contract-admin' => ['ModuleController', 'contractAdmin'],
    '/contract-admin/save' => ['ModuleController', 'saveContract'],
    '/contract-admin/events/add' => ['ModuleController', 'addContractEvent'],
    '/contract-admin/documents/upload' => ['ModuleController', 'uploadContractDocument'],
    '/contract-admin/documents/download' => ['ModuleController', 'contractDocumentDownload'],
    '/modules/projects/view' => ['ModuleController', 'projectDetail'],
    '/modules/projects/document' => ['ModuleController', 'projectDocumentDownload'],
    '/projects/assign-employee' => ['ModuleController', 'assignProjectEmployee'],
    '/projects/remove-employee' => ['ModuleController', 'removeProjectEmployee'],
    '/projects/budget/add' => ['ModuleController', 'addProjectBudget'],
    '/projects/schedule/save' => ['ModuleController', 'saveProjectSchedule'],
    '/projects/budget/delete' => ['ModuleController', 'deleteProjectBudget'],
    '/projects/save' => ['ModuleController', 'saveProject'],
    '/inventory/save' => ['ModuleController', 'saveItem'],
    '/inventory/detail' => ['ModuleController', 'itemDetail'],
    '/inventory/issue' => ['ModuleController', 'issueItem'],
    '/modules/accounting' => ['ModuleController', 'accounting'],
    '/modules/accounting/payroll' => ['ModuleController', 'accountingPayrollPortal'],
    '/modules/accounting/payroll/run' => ['ModuleController', 'processAccountingPayroll'],
    '/modules/accounting/save' => ['ModuleController', 'savePayroll'],
    '/modules/accounting/send' => ['ModuleController', 'sendPayroll'],
    '/modules/accounting/send-all' => ['ModuleController', 'bulkSendPayrolls'],
    '/modules/accounting/upload' => ['ModuleController', 'uploadPayrolls'],
    '/modules/accounting/template' => ['ModuleController', 'downloadPayrollTemplate'],
    '/management/employees' => ['ManagementController', 'employees'],
    '/management/module-access' => ['ManagementController', 'moduleAccess'],
    '/management/module-access/save' => ['ManagementController', 'saveModuleAccess'],
    '/management/roles/create' => ['ManagementController', 'createRole'],
    '/management/employees/save' => ['ManagementController', 'saveEmployee'],
    '/management/employees/view' => ['ManagementController', 'viewEmployee'],
    '/management/employees/update-photo' => ['ManagementController', 'updateEmployeePhoto'],
    '/management/employees/login-as' => ['ManagementController', 'loginAsEmployee'],
    '/management/employees/change-password' => ['ManagementController', 'changeEmployeePassword'],
    '/management/employees/custom-field' => ['ManagementController', 'addEmployeeCustomField'],
    '/management/employees/custom-field/delete' => ['ManagementController', 'deleteEmployeeCustomField'],
    '/management/employees/update' => ['ManagementController', 'updateEmployee'],
    '/management/employees/create-credentials' => ['ManagementController', 'populateEmployeeUsers'],
    '/management/employees/archive' => ['ManagementController', 'archivedEmployees'],
    '/management/employees/deactivate' => ['ManagementController', 'bulkEmployeeAction'],
    '/management/employees/template' => ['ManagementController', 'downloadEmployeeTemplate'],
    '/management/employees/upload' => ['ManagementController', 'uploadEmployees'],
    '/management/procurement' => ['ManagementController', 'procurement'],
    '/management/procurement/create' => ['ManagementController', 'createStorePurchaseOrder'],
    '/management/procurement/decision' => ['ManagementController', 'decideStorePurchaseOrder'],
    '/requisition' => ['ManagementController', 'requisition'],
    '/requisition/save' => ['ManagementController', 'saveRequisition'],
    '/requisition/inventory-search' => ['ManagementController', 'searchInventoryItems'],
    '/requisition/dispatch/approve' => ['ManagementController', 'approveDispatch'],
    '/requisition/dispatch/decide' => ['ManagementController', 'decideDispatch'],
    '/requisition/view' => ['ManagementController', 'viewRequisition'],
    '/requisition/item-adjust' => ['ManagementController', 'adjustRequisitionItemQuantity'],
    '/requisition/message' => ['ManagementController', 'addRequisitionMessage'],
    '/requisition/messages' => ['ManagementController', 'requisitionMessages'],
    '/requisition/decision' => ['ManagementController', 'decideRequisition'],
    '/requisition/handoff' => ['ManagementController', 'handoffRequisition'],
    '/management/hr' => ['ManagementController', 'hr'],
    '/management/departments/save' => ['ManagementController', 'saveDepartment'],
    '/management/departments/update-assignments' => ['ManagementController', 'updateDepartmentAssignments'],
    '/management/departments/delete' => ['ManagementController', 'deleteDepartment'],
    '/management/roles/delete' => ['ManagementController', 'deleteRole'],
    '/management/management-roles/delete' => ['ManagementController', 'deleteManagementRole'],
    '/management/salary-structures' => ['ManagementController', 'manageSalaryStructures'],
    '/management/salary-structures/save' => ['ManagementController', 'saveSalaryStructure'],
    '/management/salary-advances' => ['ManagementController', 'manageSalaryAdvances'],
    '/management/salary-advances/request' => ['ManagementController', 'requestSalaryAdvance'],
    '/management/salary-advances/approve' => ['ManagementController', 'approveSalaryAdvance'],
    '/management/salary-advances/reject' => ['ManagementController', 'rejectSalaryAdvance'],
    '/management/employee-loans' => ['ManagementController', 'manageEmployeeLoans'],
    '/management/employee-loans/create' => ['ManagementController', 'createEmployeeLoan'],
    '/management/employee-loans/view' => ['ManagementController', 'viewEmployeeLoan'],
    '/management/employee-loans/installment/paid' => ['ManagementController', 'markLoanInstallmentPaid'],
    '/management/process-payroll' => ['ManagementController', 'processPayroll'],
    '/management/payroll/run' => ['ManagementController', 'runPayroll'],
    '/management/payroll-reports' => ['ManagementController', 'payrollReports'],
    '/management/payroll-configuration' => ['ManagementController', 'payrollConfiguration'],
    '/management/payroll-configuration/save' => ['ManagementController', 'savePayrollConfiguration'],
    '/management/payroll/generate-slips' => ['ManagementController', 'generatePayslips'],
    '/management/payslip/view' => ['ManagementController', 'viewPayslip'],
    '/management/payslip/download' => ['ManagementController', 'downloadPayslipPDF'],
    '/portal/payroll' => ['ModuleController', 'portalPayroll'],
    '/portal/staff' => ['ManagementController', 'staffPortal'],
    '/portal/admin' => ['ManagementController', 'portalAdmin'],
    '/portal/hr' => ['ManagementController', 'portalHr'],
    '/portal/accountant' => ['ManagementController', 'portalAccountant'],
    '/portal/procurement-officer' => ['ManagementController', 'portalProcurementOfficer'],
    '/portal/super-admin' => ['ManagementController', 'portalSuperAdmin'],
    '/portal/managing-director' => ['ManagementController', 'portalManagingDirector'],
    '/portal/finance-manager' => ['ManagementController', 'portalFinanceManager'],
    '/portal/hr-manager' => ['ManagementController', 'portalHrManager'],
    '/portal/site-engineer' => ['ManagementController', 'portalSiteEngineer'],
    '/portal/site-quantity-surveyor' => ['ManagementController', 'portalSiteQuantitySurveyor'],
    '/portal/department-head' => ['ManagementController', 'portalDepartmentHead'],
    '/portal/logistics-officer' => ['ManagementController', 'portalLogisticsOfficer'],
];

Router::route($routes);
